name: genai pull request descriptor

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened]
    paths:
      - package-lock.json

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Ensure latest code from main (if needed)
        run: git fetch origin && git pull origin main

      - name: Run genaiscript pull request descriptor
        continue-on-error: true
        run: npx --yes genaiscript run pull_request_descriptor -prd || echo "genaiscript failed"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
